WINDOW_WIDTH = 720
WINDOW_HEIGHT = 450

GRID_WIDTH = 342
GRID_HEIGHT = 342

TILE_SIZE = 32

SHIP_POS_X = 244
SHIP_POS_Y = 216

OCEAN_GRID_X = 397
OCEAN_GRID_Y = 85
RADAR_GRID_X = 43
RADAR_GRID_POS = (RADAR_GRID_X, OCEAN_GRID_Y)

SHIP_SIZE = [2,3,3,4,5]
SHOOT_TYPES = ['radar_water', 'radar_ship', 'ocean_water', 'ocean_ship']
